M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 20, Thursday 13:11:38
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T13:11:38-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.2766Y-2.4488
X5.2766Y-2.622
T2
X5.25Y-1.3071
X8.0827Y-1.7283
X8.0866Y-3.8642
T0
M30
